# Hands-On Introduction to Machine Learning

# Part 1: Introduction to Python

<a target="_blank" href="https://colab.research.google.com/github/nunorc/hands-on-intro-ml/blob/main/notebooks/Part-1-Intro-Python.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

This notebook gives a quick introduction to the [Python](https://www.python.org/) programming language to enable anyone, with no background in computer science,  to take their first steps in learning the language. The topics briefly covered include:

1. [Variables and Basic Types](#1-variables-and-basic-types)
2. [Operators and Booleans](#2-operators-and-booleans)
3. [Native Data Structures](#3-native-data-structures)
4. [Conditional Flow](#4-conditional-flow)
5. [Loops](#5-loops)
6. [Functions](#6-functions)
7. [Classes, Objects and Instances](#7-classes-objects-and-instances)
8. [Modules and Packages](#8-modules-and-packages)

Some sections also include a couple of very simple exercises to practice the introduced concepts.

The `#` sigil indicates a comment in Python, everything after it in the same line is ignored by the interpreter.

## 1. Variables and Basic Types

In a nutshell variables are used to store values, scalars, numbers, lists,
dictionaries, etc. Think of it as a box with a name, where you can store any kind of data, that can
later be used given the box's name.

Python is not a strongly typed language, which means that you not need to define the type
of the variable, but you do need to initialize it using the assignment operator `=`.
Let's look at some examples.
To declare a new variable named `x` and initialize it with the value `10` we write:

In [1]:
x = 10

The `print()` function can be used to print, the content of a variable.
To call a function you write the name of the function followed by `()`, and include the arguments to
pass to the function between the parenthesis.
For example to print to the standard output (usually the screen) the content of variable `x`:

In [2]:
print(x)

10

We can see the output generated by calling the `print()` function above.
Variables can hold practically any kind of value.

Let's declare a new variable called `greeting` and initialize it with the string `"Hello Word!"`.
A string is just a sequence of characters and are usually used to store textual data, enclosed between double quotes or single quotes, don't worry
about the difference for now.

In [3]:
greeting = "Hello World!"

We can use again the `print()` function to inspect the variable content.

In [4]:
print(greeting)

Hello World!

In Python everything is stored as a variable. Other examples of numbers include real or complex numbers.
Some examples follow.

In [1]:
ex1 = 34.5   # float, a real number
ex2 = 3.14j  # complex
ex3 = 1e4    # scientific notation: 1x10^4

We can pass a list of arguments to the `print()` function, so they can be
printed to the screen, let's print the variables just created.

In [2]:
print(ex1, ex2, ex3)

34.5 3.14j 10000.0

### Exercises

(1.a) Create two variables, one named `name` and other named `year`, initialize them with your name
and the year you're born respectively:

In [ ]:
### insert your code here

(1.b) Print the values of your variables using the `print()` function.

In [ ]:
### insert your code here

## 2. Operators and Booleans

Operators can be used to build expressions, by combining variables, numbers, strings, etc. Arithmetic operators
can be used with variables and numbers:
addition `+`, subtraction `-`, multiplication `*`, division `/`, modulus `+` and exponent `**`,
some examples follow:

In [3]:
a = 10
b = 2

x = a + b
y = x / 2
z = 2**3   # 2^3

print(x, y, z)

12 6.0 8

Boolean operators can also be used with values and variables but return a `True` or `False`, the following cells
illustrate some examples:

In [5]:
a = 10
b = 20

a == 10

True

In [7]:
a == b

False

In [6]:
a < b

True

Boolean operators are commonly used with conditionals and loops, illustrated later.

Expressions using boolean operators can be combined using logical operators: `and`, `or`, `not` following
their typical mathematical definition:

In [8]:
a = 10
b = 20

a > 0 and b < 100

True

### Exercises

(2.a) Write an expression to store in the variable `result` the result of multiplying variable `x` and `y`.

In [ ]:
x = 10
y = 20

result = ### insert your code here

print(result)

(2.b) Write an expression that returns `True` if the value of `x` is greater than `y`

In [ ]:
x = 10
y = 20

result = ### insert your code here

print(result)

## 3. Native Data Structures

### 3.1. Lists

Lists are used to store ordered sequences of values. To create a list explicitly we use the `[]` operator, for example to create a list with the values `10`, `20`, `30`, `40` and `50` and store it in a variable `numbers` we can write:

In [7]:
numbers = [10, 20, 30, 40, 50]

Individual elements of a list can be accessed using again the `[]` operator but this time concatenated with the variable, and given the index of the element, the index of the first element in the list is always 0, so for example to print the first element of the list:

In [8]:
print(numbers[0])

10

and to print the 3rd element of the list.

In [9]:
print(numbers[2])

30

Indexes for an array can be negative, in this case they start counting from the end of the array, so for example to print the last element:

In [10]:
print(numbers[-1])

50

Arrays can also be sliced using the `:` operator, i.e. we can take a part of the array by selecting the index of the first element of the array and the last. For example to get a list of numbers from the 2nd element to the 4th element from our array `numbers` we can write:

In [11]:
numbers[1:4]

[20, 30, 40]

**Note**: that in the above cell we are not using the `print()` function, to print the values to the screen. The values appear in the output because because its' the last expression that was evaluate in this cell, and the notebook outputs its' result.

The `len()` function can be used to calculate the length of an array.

In [12]:
length = len(numbers)

print("The length of the array is", length)

The length of the array is 5

Another common function used with arrays is `sum()` that given an array calculates the summation of all elements

In [13]:
summation = sum(numbers)

print("The sum of the array is", summation)

The sum of the array is 150

### Exercises

(3.1.a) Create a variable `mylist` that contains a list of 5 numbers and print to the screen the first element of the list.

In [ ]:
### insert your code here

(3.1.b)  Write an expression that calculates the difference between the first and the elemeents
from the the variable `mylist` and store it in the `diff` variable.

In [ ]:
diff = ### insert your code here

print("The difference between the first and the last element is", diff)

### 3.2. Dictionaries

Another very common data structure, dictionaries are used to store key/value pairs. The values can the be later accessed via the key. To create a new dictionary we can use the `{}` operator, let's create a dictionary to hold information about a person, namely the person's name and age, and store it in a variable named `person`:

In [14]:
person = { "name": "John", "age": 34 }

print(person)

{'name': 'John', 'age': 34}

We can access the values of the dictionary using the key with the `[]` operator, so for example to print the value for the key `name` in the dictionary `person`:

In [15]:
print(person["name"])

John

New key/value pairs can also be added to the dictionary, for example to add a new key `hometown` to the dictionary with the value `Paris` using the assignment operator `=` we can write:

In [16]:
person["hometown"] = "Paris"

person

{'name': 'John', 'age': 34, 'hometown': 'Paris'}

We can also use the `len()` function giving an argument the dictionary, in this case we get the number of key/value pairs:

In [17]:
len(person)

3

The `person` variable that stores our dictionary is a an object so we can call methods on this object using the dot operator `.`, two common methods used are the `keys()` method which returns a list of keys in the dictionary, and the `values()` method which returns a list of values, so for example to print the list of keys and values in the `person` dictionary we can write:

In [18]:
print(person.keys(), person.values())

dict_keys(['name', 'age', 'hometown']) dict_values(['John', 34, 'Paris'])

More details on methods and objects are discussed later in this notebook.

### Exercises

(3.2.a) Create a new variable `mydict` and initialize it with a dictionary with two keys `month` and `day`
which values are the month that you were born as a string, and the day respectively.

In [ ]:
### insert your code here

(3.2.b) Complete the following print statement so that it prints the day and month that you were born, replace the `...`
with the correct code.

In [ ]:
print("I was born on day", ..., "of month", ...)

## 4. Conditional Flow

Sometimes we want to execute some code based on some condition, we can do this using the `if` keyword, followed by a boolean expression that checks for a given condition, and the if the expression returns `True` the following code block is executed. Code blocks are defined using indentation, i.e. a number of white spaces are introduced in the beginning of the line, all the lines that are indented at the same level are part of the same code block.

So for example let's create a new variable `x`, initialized with the value `15`, and then write an `if` statement that prints the message `'x is greater than 10'` only if the value stored in `x` is greater than `10`:

In [19]:
x = 15

if x > 10:
    print("x is greater than 10")

x is greater than 10

Try to change the value of `x` in the previous cell to check if the with a value lower than `10` the message is printed to screen.

The `else` keyword can also be used to define an alternative code block in case the boolean expression returns `False`, so for example to print another message in case the value in `x` is lower than `10` we can write:

In [20]:
x = 5

if x > 10:
    print("x is greater than 10")
else:
    print("x is not greater than 10")

x is not greater than 10

**Note:** remember to correctly indent your code blocks and being consistent in the number of white spaces.

### Exercises

(4.a) Write an `if` statement that compares the value of variable `x` and `y` and stores in a new variable
named `result` the difference between the larger and the smaller number.

In [ ]:
x = 10
y = 15

### insert your code here

print)"The output should be 5, your result is", result)

## 5. Loops

Loops enable repeating a code block over a sequence of values or until some condition is met.

The `for` keyword can be used to define a code block that is executed in order for every element in a list. For example example, let's create a new list `fruits` and initialize it with some fruit names:

In [21]:
fruits = ["apple", "banana", "orange"]

Now let's write a `for` loop that prints every fruit name value in the `fruits` list. We use the `in` keyword on every iteration to store the current value coming out of the array:

In [22]:
for fruit in fruits:
    print(fruit)

apple
banana
orange

Another common option for creating looks is using `while`, in this case the loop code block is executed while a condition holds true. For example to print the content of the `x` variable while it's value is less than `5`, we also increment the value of `x` on each iteration by `1` using the assignment operator `=`:

In [23]:
x = 1

while x < 5:
    print(x)
    x = x + 1

1
2
3
4

**Note:** when using `while` loops make sure that at some point the condition expression returns `False` so that the loop ends, otherwise it can run forever.

### Exercises

(5.a) Write a for loop that stores in the variable `mysum` the result of adding all the elements of the array `numbers`.

In [9]:
numbers = [10, 20, 30, 40, 50]
mysum = 0

### insert your code here

print("The sum of all numbers is", sum(numbers), "the value of mysum is", mysum)

The sum of all numbers is 150 the value of mysum is 0

## 6. Functions

Functions are used to define code blocks that can be re-used. The `def` keyword defines a new function, followed by the new function name and a list of arguments (values that you can pass to the function code block). Functions use the `return` keyword to send back their final result.

For example to define a new function called `square` that given a value `x` returns the square of that value, i.e. `x` times `x`:

In [24]:
def square(x):
    result = x * x

    return result

In the previous cell we defined a new function that we can now call anytime to execute the function code block, for example to call the `square` function giving as argument the value `3`:

In [25]:
square_of_3 = square(3)

print(square_of_3)

9

In this case we are storing the return value of the function in a variable called `square_of_3` that we then print to the scree.

**Note:** the body of a function is defined by a code block, i.e. using white space indentation.

### Exercises

(6.a) Write a function called `mult` that receives two numbers as arguments and returns the result of multiplying the two numbers.

In [ ]:
### insert your code here

print("The result of multiplying 2 and 3 is", mult(2, 3), "-- output should be 6.")

## 7. Classes, Objects and Instances

Objects are used to
A class defines the blueprint for an object, how they are created and the available attributes and methods. An object created from a class blueprint is called an instance of that object.

To create a new class we use the `class` keyword, the `__init__` special method from a class defines how new instances are created and is typically called a constructor. So to create a new class named `Person` with a constructor
that takes two arguments the new person name and age we write:

In [26]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

The `self` variable name in the previous cell is just a reference to the object that is being created.

We have defined the blueprint for creating objects for new class, i.e. create new instances of `Person`. Now, to create new instances, giving the person name and age, we can write:

In [27]:
p1 = Person("John", 25)
p2 = Person("Sarah", 22)

`p1` and `p2` are two variables that store instances of the class `Person`, we can access the `name` and `age` attributes of the object using the dot operator `.`, for example to print the `name` attribute for the instance of `p1` and the `age` attribute we can write:

In [28]:
print(p1.name, p2.age)

John 22

New methods can be added to a class definition that can be used from any instances. For example to write a new method name `say_hello` in the `Person` class to print a greeting message, we can re-write our class definition as:

In [29]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def say_hello(self):
        print("Hello, my name is " + self.name)

The new method introduced, as all methods in a class, is given as the first argument `self`, a reference to the instance object, from which we get the value of the `name` attribute and concatenate with a string using the `+` operator.

After we updated the `Person` class definition we can create a new object, instance of this class, and call the `say_hello()` method from the instance to get the print for the message:

In [30]:
p3 = Person("Ann", 24)

p3.say_hello()

Hello, my name is Ann

### Exercises

(7.a) Create a new variable named `me` and initialize it with a new instance of person, giving your name and
age as arguments.

In [ ]:
### insert your code here

(7.b) Complete the following `print()` statement so that a correct sentence is printed to the screen, replace the '...'.

In [ ]:
print)"My name is", ..., "and I'm", ..., "years old.")

## 8. Modules and Packages

Modules enable organizing code for larger code bases in different files, or for different topics or goals. A module is just a file that includes code that can be used from other programs or scripts, this usually includes class definitions and functions. Modules are distributed in packages that can be shared.
Packages can be installed for example using the `pip` command line tool.
For example to install the `requests` package we can run the following command from a command line or bash:

```shell
$ pip install requests
```

Discussing how to implement our own packages is out of scope for this workshop, but let's take a quick look on
how we can use other modules in our code.
To be able to use a module from a package we need to use the `import` keyword, for example to import the `requests` package we write:

In [31]:
import requests

The we can use the `get` method from the package to perform a HTTP request to a webpage and store the result of performing the operation in a variable called `result`:

In [32]:
result = requests.get("https://catfact.ninja/fact")

We can check the result of calling this webpage by inspecting the `text` attribute from the `result` variable:

In [33]:
result.text

'{"fact":"Cats have supersonic hearing","length":28}'

The `requests` package is one of the most popular approaches for handling HTTP requests.

Let's quickly look at another popular package `numpy` for handling large, multi-dimensional arrays and matrices. We can install the package if not available with:

```shell
$ pip install numpy
```

Once the package is installed we can make it available in our code using the `import` keyword, and this time we give it an alias using the `as` keyword so that we only need to write `np` to access it:

In [34]:
import numpy as np

We can now create a new variable using the `array` class from the `numpy` package to store a matrix:

In [35]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])

A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

We can use the `identity` class to create a new identity matrix of degree 3:

In [36]:
I = np.identity(3)

I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

We can use the `shape` method from our matrixes variables to inspect the shape of the matrix, i.e. the number of rows and columns respectively:

In [37]:
print(A.shape, I.shape)

(3, 3) (3, 3)

We can now for example add the two matrices:

In [38]:
A + I

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

Or calculate the dot product using the `dot` method from the matrix `A` variable:

In [39]:
A.dot(I)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

Although the `requests` and `numpy` examples illustrated are quite trivial, there is a lot of details going on behind the scenes that are being handled for the user, being a good Python developer includes knowing about some of these packages that can make writing programs simpler and faster. Here is a quick list of some other popular packages that you should at least know about:

* [requests](https://requests.readthedocs.io/en/latest/) -- HTTP requests library
* [numpy](https://numpy.org/) -- numerical arrays and matrices library
* [scipy](https://scipy.org/) -- fundamental algorithms for scientific computing
* [scikit-learn](https://scikit-learn.org/) -- Machine Learning library
* [tensorflow](https://www.tensorflow.org/) -- Deep Learning library
* [matplotlib](https://matplotlib.org/) -- data visualization and plotting
* [pandas](https://pandas.pydata.org/) -- data analysis and manipulation
* [ipython](https://ipython.org/) -- interactive Python shell
* [jupyter](https://jupyter.org/) -- jupyter lab and notebooks

**Congratulations!** You completed the *Part 1: Introduction to Python* notebook!

Pour yourself a cup of your favorite drink and take a minute to enjoy your first steps in mastering Python.